name: Deploy Binance Future to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt' # or 'zulu', 'temurin', etc.
          java-version: '11'

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.PRIVATE_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      - name: Deploy with rsync
        run: rsync -avz ./ ${{ secrets.USERNAME }}@${{ secrets.HOST }}:~/.ssh/Binance-future-Project-2
      
      # - name: Build with Gradle
      #   run: ./gradlew build
      
      # - name: Deploy Binance Future to DigitalOcean
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.HOST }}
      #     username: ${{ secrets.USERNAME }}
      #     key: ${{ secrets.PRIVATE_KEY }}
      #     script: |
      #       cd /var/www/my-app
      #       rm -rf *
      #       unzip /path/to/build/zip
